/**
 * Store re-exports from db (SQLite, persisted to server file).
 * All state and mutations go through the SQLite backend.
 */
export type { User, UserRow } from './db'
export {
  init,
  getState,
  subscribe,
  exportDatabase,
  loadDatabaseFromBuffer,
  hasServerDbApi,
  getCurrentUser,
  setCurrentUserId,
  setDefaultBranchPersonId,
  login,
  createUserByAdmin,
  getUsers,
  updateUserByAdmin,
  deleteUserByAdmin,
  logout,
  addPerson,
  importPerson,
  updatePerson,
  deletePerson,
  addParentChild,
  addParentChildInLaw,
  addParentChildAdopt,
  addSpouse,
  removeRelationship,
  getPerson,
  getChildrenIds,
  getParentIds,
  getSpouseId,
  getSpouseIds,
  getSpouseRelationships,
  getParentRelationships,
  getChildRelationships,
  getSpouseRelationship,
} from './db'
